/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FileMetadata = IDL.Record({
  'path' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });
export const UserProfileWithChangeStatus = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'hasChangedName' : IDL.Bool,
});
export const StreamingToken = IDL.Record({
  'resource' : IDL.Text,
  'index' : IDL.Nat,
});
export const StreamingCallbackHttpResponse = IDL.Record({
  'token' : IDL.Opt(StreamingToken),
  'body' : IDL.Vec(IDL.Nat8),
});
export const HeaderField = IDL.Tuple(IDL.Text, IDL.Text);
export const HttpRequest = IDL.Record({
  'url' : IDL.Text,
  'method' : IDL.Text,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HeaderField),
});
export const StreamingCallback = IDL.Func(
    [StreamingToken],
    [StreamingCallbackHttpResponse],
    ['query'],
  );
export const StreamingStrategy = IDL.Variant({
  'Callback' : IDL.Record({
    'token' : StreamingToken,
    'callback' : StreamingCallback,
  }),
});
export const HttpResponse = IDL.Record({
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HeaderField),
  'streaming_strategy' : IDL.Opt(StreamingStrategy),
  'status_code' : IDL.Nat16,
});
export const UserInfo = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
  'approval' : ApprovalStatus,
});
export const GameStatistics = IDL.Record({
  'totalShotsFired' : IDL.Nat,
  'totalChickensShot' : IDL.Nat,
  'bestSessionChickens' : IDL.Nat,
  'bestConsecutiveHits' : IDL.Nat,
  'highestScore' : IDL.Nat,
  'perfectAccuracySessions' : IDL.Nat,
  'smallChickensShot' : IDL.Nat,
  'totalPlayTimeMinutes' : IDL.Nat,
  'level' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'fastChickensShot' : IDL.Nat,
  'largeChickensShot' : IDL.Nat,
  'totalMissedShots' : IDL.Nat,
  'mediumChickensShot' : IDL.Nat,
  'currentAccuracy' : IDL.Float64,
  'goldenChickensShot' : IDL.Nat,
});

export const idlService = IDL.Service({
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'fileDelete' : IDL.Func([IDL.Text], [], []),
  'fileList' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'fileUpload' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Bool],
      [],
      [],
    ),
  'getApprovalStatus' : IDL.Func([IDL.Principal], [ApprovalStatus], ['query']),
  'getCurrentUserApprovalStatus' : IDL.Func([], [ApprovalStatus], ['query']),
  'getCurrentUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCurrentUserProfileWithChangeStatus' : IDL.Func(
      [],
      [IDL.Opt(UserProfileWithChangeStatus)],
      ['query'],
    ),
  'getCurrentUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileWithChangeStatus' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileWithChangeStatus)],
      ['query'],
    ),
  'httpStreamingCallback' : IDL.Func(
      [StreamingToken],
      [StreamingCallbackHttpResponse],
      ['query'],
    ),
  'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
  'initializeAuth' : IDL.Func([], [], []),
  'isCurrentUserAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
  'saveCurrentUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCurrentUserProfileWithChangeStatus' : IDL.Func(
      [UserProfileWithChangeStatus],
      [],
      [],
    ),
  'saveGameStatistics' : IDL.Func([GameStatistics], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FileMetadata = IDL.Record({
    'path' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });
  const UserProfileWithChangeStatus = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'hasChangedName' : IDL.Bool,
  });
  const StreamingToken = IDL.Record({
    'resource' : IDL.Text,
    'index' : IDL.Nat,
  });
  const StreamingCallbackHttpResponse = IDL.Record({
    'token' : IDL.Opt(StreamingToken),
    'body' : IDL.Vec(IDL.Nat8),
  });
  const HeaderField = IDL.Tuple(IDL.Text, IDL.Text);
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HeaderField),
  });
  const StreamingCallback = IDL.Func(
      [StreamingToken],
      [StreamingCallbackHttpResponse],
      ['query'],
    );
  const StreamingStrategy = IDL.Variant({
    'Callback' : IDL.Record({
      'token' : StreamingToken,
      'callback' : StreamingCallback,
    }),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HeaderField),
    'streaming_strategy' : IDL.Opt(StreamingStrategy),
    'status_code' : IDL.Nat16,
  });
  const UserInfo = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
    'approval' : ApprovalStatus,
  });
  const GameStatistics = IDL.Record({
    'totalShotsFired' : IDL.Nat,
    'totalChickensShot' : IDL.Nat,
    'bestSessionChickens' : IDL.Nat,
    'bestConsecutiveHits' : IDL.Nat,
    'highestScore' : IDL.Nat,
    'perfectAccuracySessions' : IDL.Nat,
    'smallChickensShot' : IDL.Nat,
    'totalPlayTimeMinutes' : IDL.Nat,
    'level' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'fastChickensShot' : IDL.Nat,
    'largeChickensShot' : IDL.Nat,
    'totalMissedShots' : IDL.Nat,
    'mediumChickensShot' : IDL.Nat,
    'currentAccuracy' : IDL.Float64,
    'goldenChickensShot' : IDL.Nat,
  });
  
  return IDL.Service({
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'fileDelete' : IDL.Func([IDL.Text], [], []),
    'fileList' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'fileUpload' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Bool],
        [],
        [],
      ),
    'getApprovalStatus' : IDL.Func(
        [IDL.Principal],
        [ApprovalStatus],
        ['query'],
      ),
    'getCurrentUserApprovalStatus' : IDL.Func([], [ApprovalStatus], ['query']),
    'getCurrentUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCurrentUserProfileWithChangeStatus' : IDL.Func(
        [],
        [IDL.Opt(UserProfileWithChangeStatus)],
        ['query'],
      ),
    'getCurrentUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileWithChangeStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileWithChangeStatus)],
        ['query'],
      ),
    'httpStreamingCallback' : IDL.Func(
        [StreamingToken],
        [StreamingCallbackHttpResponse],
        ['query'],
      ),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'initializeAuth' : IDL.Func([], [], []),
    'isCurrentUserAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
    'saveCurrentUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCurrentUserProfileWithChangeStatus' : IDL.Func(
        [UserProfileWithChangeStatus],
        [],
        [],
      ),
    'saveGameStatistics' : IDL.Func([GameStatistics], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };