/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JoinMode = IDL.Variant({
  'open' : IDL.Null,
  'requestRequired' : IDL.Null,
});
export const FileMetadata = IDL.Record({
  'path' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
});
export const ClanSummary = IDL.Record({
  'id' : IDL.Nat,
  'ownerId' : IDL.Principal,
  'joinMode' : JoinMode,
  'name' : IDL.Text,
  'memberCount' : IDL.Nat,
  'description' : IDL.Text,
  'maxMembers' : IDL.Nat,
  'emblemId' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PumpPriceData = IDL.Record({
  'change24h' : IDL.Float64,
  'lastUpdated' : IDL.Int,
  'price' : IDL.Float64,
});
export const PrincipalInfo = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'level' : IDL.Nat,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const ClanDetails = IDL.Record({
  'id' : IDL.Nat,
  'pendingCount' : IDL.Nat,
  'members' : IDL.Vec(PrincipalInfo),
  'ownerId' : IDL.Principal,
  'joinMode' : JoinMode,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'memberCount' : IDL.Nat,
  'description' : IDL.Text,
  'maxMembers' : IDL.Nat,
  'emblemId' : IDL.Nat,
});
export const ClanMessage = IDL.Record({
  'id' : IDL.Nat,
  'clanId' : IDL.Nat,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderId' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'telegramUrl' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'xUrl' : IDL.Opt(IDL.Text),
  'githubUrl' : IDL.Opt(IDL.Text),
  'profilePictureUrl' : IDL.Opt(IDL.Text),
  'bannerImageUrl' : IDL.Opt(IDL.Text),
  'youtubeUrl' : IDL.Opt(IDL.Text),
});
export const UserProfileWithChangeStatus = IDL.Record({
  'bio' : IDL.Text,
  'telegramUrl' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'hasChangedName' : IDL.Bool,
  'xUrl' : IDL.Opt(IDL.Text),
  'githubUrl' : IDL.Opt(IDL.Text),
  'youtubeUrl' : IDL.Opt(IDL.Text),
});
export const DirectMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
  'recipientId' : IDL.Principal,
  'senderId' : IDL.Principal,
});
export const GameStatistics = IDL.Record({
  'totalShotsFired' : IDL.Nat,
  'totalChickensShot' : IDL.Nat,
  'bestSessionChickens' : IDL.Nat,
  'bestConsecutiveHits' : IDL.Nat,
  'highestScore' : IDL.Nat,
  'perfectAccuracySessions' : IDL.Nat,
  'smallChickensShot' : IDL.Nat,
  'totalPlayTimeMinutes' : IDL.Nat,
  'level' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'fastChickensShot' : IDL.Nat,
  'largeChickensShot' : IDL.Nat,
  'totalMissedShots' : IDL.Nat,
  'mediumChickensShot' : IDL.Nat,
  'currentAccuracy' : IDL.Float64,
  'goldenChickensShot' : IDL.Nat,
});
export const StreamingToken = IDL.Record({
  'resource' : IDL.Text,
  'index' : IDL.Nat,
});
export const StreamingCallbackHttpResponse = IDL.Record({
  'token' : IDL.Opt(StreamingToken),
  'body' : IDL.Vec(IDL.Nat8),
});
export const HeaderField = IDL.Tuple(IDL.Text, IDL.Text);
export const HttpRequest = IDL.Record({
  'url' : IDL.Text,
  'method' : IDL.Text,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HeaderField),
});
export const StreamingCallback = IDL.Func(
    [StreamingToken],
    [StreamingCallbackHttpResponse],
    ['query'],
  );
export const StreamingStrategy = IDL.Variant({
  'Callback' : IDL.Record({
    'token' : StreamingToken,
    'callback' : StreamingCallback,
  }),
});
export const HttpResponse = IDL.Record({
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HeaderField),
  'streaming_strategy' : IDL.Opt(StreamingStrategy),
  'status_code' : IDL.Nat16,
});
export const UserInfo = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
  'approval' : ApprovalStatus,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpResponseRaw = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  'addFriend' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'approveJoinRequest' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClan' : IDL.Func(
      [IDL.Text, IDL.Text, JoinMode, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'declineJoinRequest' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteClan' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'fileDelete' : IDL.Func([IDL.Text], [], []),
  'fileList' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'fileUpload' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Bool],
      [],
      [],
    ),
  'getAllClans' : IDL.Func([], [IDL.Vec(ClanSummary)], ['query']),
  'getApprovalStatus' : IDL.Func([IDL.Principal], [ApprovalStatus], ['query']),
  'getCachedPumpFunPrice' : IDL.Func([], [PumpPriceData], ['query']),
  'getClan' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : ClanDetails, 'err' : IDL.Text })],
      ['query'],
    ),
  'getClanMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Vec(ClanMessage), 'err' : IDL.Text })],
      ['query'],
    ),
  'getCurrentUserApprovalStatus' : IDL.Func([], [ApprovalStatus], ['query']),
  'getCurrentUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCurrentUserProfileWithChangeStatus' : IDL.Func(
      [],
      [IDL.Opt(UserProfileWithChangeStatus)],
      ['query'],
    ),
  'getCurrentUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDirectMessages' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Vec(DirectMessage), 'err' : IDL.Text })],
      ['query'],
    ),
  'getFriends' : IDL.Func([], [IDL.Vec(PrincipalInfo)], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getPendingJoinRequests' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(PrincipalInfo), 'err' : IDL.Text })],
      [],
    ),
  'getPumpFunPrice' : IDL.Func([], [PumpPriceData], []),
  'getUserGameStats' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(GameStatistics)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileWithChangeStatus' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileWithChangeStatus)],
      ['query'],
    ),
  'httpStreamingCallback' : IDL.Func(
      [StreamingToken],
      [StreamingCallbackHttpResponse],
      ['query'],
    ),
  'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
  'initializeAuth' : IDL.Func([], [], []),
  'isCurrentUserAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFriend' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'joinClan' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'leaveClan' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'listUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
  'removeFriend' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'saveCurrentUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCurrentUserProfileWithChangeStatus' : IDL.Func(
      [UserProfileWithChangeStatus],
      [],
      [],
    ),
  'saveGameStatistics' : IDL.Func([GameStatistics], [], []),
  'searchClans' : IDL.Func([IDL.Text], [IDL.Vec(ClanSummary)], ['query']),
  'sendClanMessage' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : ClanMessage, 'err' : IDL.Text })],
      [],
    ),
  'sendDirectMessage' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Variant({ 'ok' : DirectMessage, 'err' : IDL.Text })],
      [],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'transformPumpResponse' : IDL.Func(
      [HttpResponseRaw],
      [HttpResponseRaw],
      ['query'],
    ),
  'updateClan' : IDL.Func(
      [IDL.Nat, IDL.Text, JoinMode, IDL.Nat],
      [IDL.Variant({ 'ok' : ClanDetails, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JoinMode = IDL.Variant({
    'open' : IDL.Null,
    'requestRequired' : IDL.Null,
  });
  const FileMetadata = IDL.Record({
    'path' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
  });
  const ClanSummary = IDL.Record({
    'id' : IDL.Nat,
    'ownerId' : IDL.Principal,
    'joinMode' : JoinMode,
    'name' : IDL.Text,
    'memberCount' : IDL.Nat,
    'description' : IDL.Text,
    'maxMembers' : IDL.Nat,
    'emblemId' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PumpPriceData = IDL.Record({
    'change24h' : IDL.Float64,
    'lastUpdated' : IDL.Int,
    'price' : IDL.Float64,
  });
  const PrincipalInfo = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'level' : IDL.Nat,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const ClanDetails = IDL.Record({
    'id' : IDL.Nat,
    'pendingCount' : IDL.Nat,
    'members' : IDL.Vec(PrincipalInfo),
    'ownerId' : IDL.Principal,
    'joinMode' : JoinMode,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'memberCount' : IDL.Nat,
    'description' : IDL.Text,
    'maxMembers' : IDL.Nat,
    'emblemId' : IDL.Nat,
  });
  const ClanMessage = IDL.Record({
    'id' : IDL.Nat,
    'clanId' : IDL.Nat,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'telegramUrl' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'xUrl' : IDL.Opt(IDL.Text),
    'githubUrl' : IDL.Opt(IDL.Text),
    'profilePictureUrl' : IDL.Opt(IDL.Text),
    'bannerImageUrl' : IDL.Opt(IDL.Text),
    'youtubeUrl' : IDL.Opt(IDL.Text),
  });
  const UserProfileWithChangeStatus = IDL.Record({
    'bio' : IDL.Text,
    'telegramUrl' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'hasChangedName' : IDL.Bool,
    'xUrl' : IDL.Opt(IDL.Text),
    'githubUrl' : IDL.Opt(IDL.Text),
    'youtubeUrl' : IDL.Opt(IDL.Text),
  });
  const DirectMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
    'recipientId' : IDL.Principal,
    'senderId' : IDL.Principal,
  });
  const GameStatistics = IDL.Record({
    'totalShotsFired' : IDL.Nat,
    'totalChickensShot' : IDL.Nat,
    'bestSessionChickens' : IDL.Nat,
    'bestConsecutiveHits' : IDL.Nat,
    'highestScore' : IDL.Nat,
    'perfectAccuracySessions' : IDL.Nat,
    'smallChickensShot' : IDL.Nat,
    'totalPlayTimeMinutes' : IDL.Nat,
    'level' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'fastChickensShot' : IDL.Nat,
    'largeChickensShot' : IDL.Nat,
    'totalMissedShots' : IDL.Nat,
    'mediumChickensShot' : IDL.Nat,
    'currentAccuracy' : IDL.Float64,
    'goldenChickensShot' : IDL.Nat,
  });
  const StreamingToken = IDL.Record({
    'resource' : IDL.Text,
    'index' : IDL.Nat,
  });
  const StreamingCallbackHttpResponse = IDL.Record({
    'token' : IDL.Opt(StreamingToken),
    'body' : IDL.Vec(IDL.Nat8),
  });
  const HeaderField = IDL.Tuple(IDL.Text, IDL.Text);
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HeaderField),
  });
  const StreamingCallback = IDL.Func(
      [StreamingToken],
      [StreamingCallbackHttpResponse],
      ['query'],
    );
  const StreamingStrategy = IDL.Variant({
    'Callback' : IDL.Record({
      'token' : StreamingToken,
      'callback' : StreamingCallback,
    }),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HeaderField),
    'streaming_strategy' : IDL.Opt(StreamingStrategy),
    'status_code' : IDL.Nat16,
  });
  const UserInfo = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
    'approval' : ApprovalStatus,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpResponseRaw = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    'addFriend' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'approveJoinRequest' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClan' : IDL.Func(
        [IDL.Text, IDL.Text, JoinMode, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'declineJoinRequest' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteClan' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'fileDelete' : IDL.Func([IDL.Text], [], []),
    'fileList' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'fileUpload' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Bool],
        [],
        [],
      ),
    'getAllClans' : IDL.Func([], [IDL.Vec(ClanSummary)], ['query']),
    'getApprovalStatus' : IDL.Func(
        [IDL.Principal],
        [ApprovalStatus],
        ['query'],
      ),
    'getCachedPumpFunPrice' : IDL.Func([], [PumpPriceData], ['query']),
    'getClan' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : ClanDetails, 'err' : IDL.Text })],
        ['query'],
      ),
    'getClanMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Vec(ClanMessage), 'err' : IDL.Text })],
        ['query'],
      ),
    'getCurrentUserApprovalStatus' : IDL.Func([], [ApprovalStatus], ['query']),
    'getCurrentUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCurrentUserProfileWithChangeStatus' : IDL.Func(
        [],
        [IDL.Opt(UserProfileWithChangeStatus)],
        ['query'],
      ),
    'getCurrentUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDirectMessages' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Vec(DirectMessage), 'err' : IDL.Text })],
        ['query'],
      ),
    'getFriends' : IDL.Func([], [IDL.Vec(PrincipalInfo)], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getPendingJoinRequests' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(PrincipalInfo), 'err' : IDL.Text })],
        [],
      ),
    'getPumpFunPrice' : IDL.Func([], [PumpPriceData], []),
    'getUserGameStats' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(GameStatistics)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileWithChangeStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileWithChangeStatus)],
        ['query'],
      ),
    'httpStreamingCallback' : IDL.Func(
        [StreamingToken],
        [StreamingCallbackHttpResponse],
        ['query'],
      ),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'initializeAuth' : IDL.Func([], [], []),
    'isCurrentUserAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFriend' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'joinClan' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'leaveClan' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'listUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
    'removeFriend' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'saveCurrentUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCurrentUserProfileWithChangeStatus' : IDL.Func(
        [UserProfileWithChangeStatus],
        [],
        [],
      ),
    'saveGameStatistics' : IDL.Func([GameStatistics], [], []),
    'searchClans' : IDL.Func([IDL.Text], [IDL.Vec(ClanSummary)], ['query']),
    'sendClanMessage' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : ClanMessage, 'err' : IDL.Text })],
        [],
      ),
    'sendDirectMessage' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Variant({ 'ok' : DirectMessage, 'err' : IDL.Text })],
        [],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'transformPumpResponse' : IDL.Func(
        [HttpResponseRaw],
        [HttpResponseRaw],
        ['query'],
      ),
    'updateClan' : IDL.Func(
        [IDL.Nat, IDL.Text, JoinMode, IDL.Nat],
        [IDL.Variant({ 'ok' : ClanDetails, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };