/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ClanDetails {
  'id' : bigint,
  'pendingCount' : bigint,
  'members' : Array<PrincipalInfo>,
  'ownerId' : Principal,
  'joinMode' : JoinMode,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
}
export interface ClanMessage {
  'id' : bigint,
  'clanId' : bigint,
  'text' : string,
  'timestamp' : bigint,
  'senderId' : Principal,
}
export interface ClanSummary {
  'id' : bigint,
  'ownerId' : Principal,
  'joinMode' : JoinMode,
  'name' : string,
  'memberCount' : bigint,
  'description' : string,
}
export interface FileMetadata {
  'path' : string,
  'size' : bigint,
  'mimeType' : string,
}
export interface GameStatistics {
  'totalShotsFired' : bigint,
  'totalChickensShot' : bigint,
  'bestSessionChickens' : bigint,
  'bestConsecutiveHits' : bigint,
  'highestScore' : bigint,
  'perfectAccuracySessions' : bigint,
  'smallChickensShot' : bigint,
  'totalPlayTimeMinutes' : bigint,
  'level' : bigint,
  'totalScore' : bigint,
  'fastChickensShot' : bigint,
  'largeChickensShot' : bigint,
  'totalMissedShots' : bigint,
  'mediumChickensShot' : bigint,
  'currentAccuracy' : number,
  'goldenChickensShot' : bigint,
}
export type HeaderField = [string, string];
export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<HeaderField>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<HeaderField>,
  'streaming_strategy' : [] | [StreamingStrategy],
  'status_code' : number,
}
export type JoinMode = { 'open' : null } |
  { 'requestRequired' : null };
export interface PrincipalInfo {
  'principal' : Principal,
  'name' : string,
  'level' : bigint,
  'avatarUrl' : [] | [string],
}
export type StreamingCallback = ActorMethod<
  [StreamingToken],
  StreamingCallbackHttpResponse
>;
export interface StreamingCallbackHttpResponse {
  'token' : [] | [StreamingToken],
  'body' : Uint8Array,
}
export type StreamingStrategy = {
    'Callback' : { 'token' : StreamingToken, 'callback' : [Principal, string] }
  };
export interface StreamingToken { 'resource' : string, 'index' : bigint }
export interface UserInfo {
  'principal' : Principal,
  'role' : UserRole,
  'approval' : ApprovalStatus,
}
export interface UserProfile { 'bio' : string, 'name' : string }
export interface UserProfileWithChangeStatus {
  'bio' : string,
  'name' : string,
  'hasChangedName' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addFriend' : ActorMethod<
    [Principal],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'approveJoinRequest' : ActorMethod<
    [bigint, Principal],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClan' : ActorMethod<
    [string, string, JoinMode],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'declineJoinRequest' : ActorMethod<
    [bigint, Principal],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteClan' : ActorMethod<[bigint], { 'ok' : string } | { 'err' : string }>,
  'fileDelete' : ActorMethod<[string], undefined>,
  'fileList' : ActorMethod<[], Array<FileMetadata>>,
  'fileUpload' : ActorMethod<[string, string, Uint8Array, boolean], undefined>,
  'getAllClans' : ActorMethod<[], Array<ClanSummary>>,
  'getApprovalStatus' : ActorMethod<[Principal], ApprovalStatus>,
  'getClan' : ActorMethod<
    [bigint],
    { 'ok' : ClanDetails } |
      { 'err' : string }
  >,
  'getClanMessages' : ActorMethod<
    [bigint, bigint, [] | [bigint]],
    { 'ok' : Array<ClanMessage> } |
      { 'err' : string }
  >,
  'getCurrentUserApprovalStatus' : ActorMethod<[], ApprovalStatus>,
  'getCurrentUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCurrentUserProfileWithChangeStatus' : ActorMethod<
    [],
    [] | [UserProfileWithChangeStatus]
  >,
  'getCurrentUserRole' : ActorMethod<[], UserRole>,
  'getFriends' : ActorMethod<[], Array<PrincipalInfo>>,
  'getLeaderboard' : ActorMethod<[], Array<[string, bigint, bigint]>>,
  'getPendingJoinRequests' : ActorMethod<
    [bigint],
    { 'ok' : Array<PrincipalInfo> } |
      { 'err' : string }
  >,
  'getUserGameStats' : ActorMethod<[Principal], [] | [GameStatistics]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileWithChangeStatus' : ActorMethod<
    [Principal],
    [] | [UserProfileWithChangeStatus]
  >,
  'httpStreamingCallback' : ActorMethod<
    [StreamingToken],
    StreamingCallbackHttpResponse
  >,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'initializeAuth' : ActorMethod<[], undefined>,
  'isCurrentUserAdmin' : ActorMethod<[], boolean>,
  'isFriend' : ActorMethod<[Principal], boolean>,
  'joinClan' : ActorMethod<[bigint], { 'ok' : string } | { 'err' : string }>,
  'leaveClan' : ActorMethod<[bigint], { 'ok' : string } | { 'err' : string }>,
  'listUsers' : ActorMethod<[], Array<UserInfo>>,
  'removeFriend' : ActorMethod<
    [Principal],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveCurrentUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCurrentUserProfileWithChangeStatus' : ActorMethod<
    [UserProfileWithChangeStatus],
    undefined
  >,
  'saveGameStatistics' : ActorMethod<[GameStatistics], undefined>,
  'searchClans' : ActorMethod<[string], Array<ClanSummary>>,
  'sendClanMessage' : ActorMethod<
    [bigint, string],
    { 'ok' : ClanMessage } |
      { 'err' : string }
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];